# Generated by Django 3.2.4 on 2022-05-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_id', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('sentences', models.TextField()),
            ],
        ),
    ]
